#!/usr/bin/env python3
"""Exercise the real GTK/WebKit runtime with disposable documents and isolated state.

Run from a graphical desktop session:
  /usr/bin/python3 tests/native_smoke.py --output work/native-check
The actual user README is opened read-only and its hash is checked afterwards.
This does not substitute for a human check of file-picker and physical input UX.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import traceback

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from markdown_reader.app import Document, ReaderApplication, GLib, Gtk, WebKit
from gi.repository import Graphene

ACTUAL_README = Path(os.environ.get("MR_TEST_DOCUMENT", PROJECT / "README.md")).expanduser().resolve()
COMPREHENSIVE = r'''---
title: Native rendering verification
owner: Markdown Reader test
---
# A clearer place for your thoughts

This disposable document checks **beautiful reading**, _visual editing_, and
the fidelity of Markdown generated by an agent. Unicode: café, λ, हिन्दी.

## A small comparison

| Capability | Result |
| :--- | ---: |
| Tables | 42 |
| **Formatting** | 100% |

- [x] Render a document
- [ ] Preserve unsaved edits

> [!NOTE] A useful detail
> This callout remains part of the original document.

![Local test image](local%20image.svg)

## Code is still code

```python title="example.py" {1}
print("Hello, Markdown")
```

```latex
\frac{this}{remains-code}
```

## Mathematics and a diagram

Inline maths $E=mc^2$ accompanies display notation:

$$
\int_0^1 x^2\,dx = \frac{1}{3}
$$

```mermaid
flowchart LR
    Read --> Edit
    Edit --> Save
```

A source note.[^evidence]

[^evidence]: Footnote text remains associated with its label.

<div class="fixture-html">Safe embedded HTML is visible.</div>

[A local document](editing.md) and [a web reference](https://example.com).
'''


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


class NativeSmoke:
    def __init__(self, output: Path):
        if not Gtk.init_check():
            raise SystemExit("Native integration needs access to a graphical desktop session.")
        original_call = Document.call
        def testing_call(document, method, *arguments):
            if method == "load" and arguments:
                arguments = ({**arguments[0], "debug": True}, *arguments[1:])
            return original_call(document, method, *arguments)
        Document.call = testing_call
        if os.environ.get("MR_DEBUG"):
            original_resource = ReaderApplication._resource
            def resource_debug(application, request):
                print(json.dumps({"resource_request": request.get_uri()}), flush=True)
                return original_resource(application, request)
            ReaderApplication._resource = resource_debug
        self.output = output.resolve()
        self.output.mkdir(parents=True, exist_ok=True)
        self.build_hash = sha(PROJECT / "frontend/dist/index.html")
        # Each run gets new state; repeated runs must never show recovery prompts.
        self.run_dir = self.output / f"run-{time.time_ns()}"
        self.fixtures = self.run_dir / "fixtures"
        self.fixtures.mkdir(parents=True)
        self.document_path = self.fixtures / "Résumé # 50%.md"
        self.document_path.write_text(COMPREHENSIVE)
        self.edit_path = self.fixtures / "editing.md"
        self.edit_path.write_text("# Editable document\n\nInitial paragraph.\n\n![Local](local%20image.svg)\n\n[Related](linked.md)\n")
        (self.fixtures / "linked.md").write_text("# A related document\n")
        (self.fixtures / "local image.svg").write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" width="560" height="112" viewBox="0 0 560 112">'
            '<rect width="560" height="112" rx="14" fill="#edf2fa"/>'
            '<circle cx="55" cy="56" r="25" fill="#547cc2"/>'
            '<text x="100" y="64" font-family="sans-serif" font-size="22" fill="#2e466d">Local images, correctly resolved.</text></svg>'
        )
        self.initial_hash = sha(self.document_path)
        self.actual_hash = sha(ACTUAL_README) if ACTUAL_README.exists() else None
        self.app = ReaderApplication(application_id=f"local.markdownreader.NativeSmoke.p{os.getpid()}",
                                     state_dir=self.run_dir / "state", restore=False)
        self.app.connect("activate", lambda *_: GLib.idle_add(self.start))
        self.results: list[dict] = []
        self.done = False
        self.failed = False
        self.start_time = time.monotonic()
        self.doc = None
        self.edit_doc = None
        self.window = None
        GLib.timeout_add_seconds(240, lambda: self.fail("Overall native integration timeout (240 seconds)"))

    def record(self, name, detail=None, status="passed"):
        result = {"name": name, "status": status}
        if detail is not None:
            result["detail"] = detail
        self.results.append(result)
        print(json.dumps(result), flush=True)

    def guard(self, function):
        def guarded(*args):
            if self.done:
                return GLib.SOURCE_REMOVE
            try:
                return function(*args)
            except Exception as error:
                traceback.print_exc()
                return self.fail(f"{function.__name__}: {error}")
        return guarded

    def require(self, condition, message):
        if not condition:
            raise AssertionError(message)

    def wait_for(self, condition, then, label, timeout=45):
        deadline = time.monotonic() + timeout
        @self.guard
        def tick():
            if condition():
                then()
                return GLib.SOURCE_REMOVE
            if time.monotonic() >= deadline:
                diagnostic = {"ready": self.doc.ready, "loaded": self.doc.loaded,
                              "banner": self.doc.banner_label.get_text()} if self.doc else {}
                return self.fail(f"Timed out waiting for {label}: {diagnostic}")
            return GLib.SOURCE_CONTINUE
        GLib.timeout_add(100, tick)

    def wait_mode(self, doc, target, then, timeout=45):
        """Wait for the native acknowledgement and the corresponding visible DOM."""
        deadline = time.monotonic() + timeout

        @self.guard
        def retry():
            self.require(time.monotonic() < deadline,
                         f"Timed out waiting for {target} mode: loaded={doc.loaded}, "
                         f"mode={doc.mode}, busy={doc.mode_busy}, reason={doc.edit_reason}")
            if doc.loaded and doc.mode == target and not doc.mode_busy:
                self.evaluate(doc, """(()=>{const state=window.reader.inspect();return {
                    mode:state.mode,busy:!!state.busy,editorReady:!!state.editorReady,
                    editor:!!document.querySelector('#editor .ProseMirror'),
                    reading:!!document.querySelector('#editor .reading-document')};})()""", inspected)
            else:
                GLib.timeout_add(75, retry)
            return GLib.SOURCE_REMOVE

        def inspected(state):
            visible = state["editor"] and state["editorReady"] if target == "edit" else state["reading"] and not state["editor"]
            if (doc.loaded and doc.mode == target and not doc.mode_busy
                    and state["mode"] == target and not state["busy"] and visible):
                then()
            else:
                GLib.timeout_add(75, retry)

        retry()

    def delay(self, then, milliseconds=300):
        GLib.timeout_add(milliseconds, self.guard(lambda: (then(), GLib.SOURCE_REMOVE)[1]))

    def evaluate(self, doc, expression, then):
        @self.guard
        def result(value, error):
            if error:
                raise error
            then(json.loads(value.to_string()))
        doc.js(f"JSON.stringify(({expression}))", result)

    def start(self):
        try:
            self.window = self.app.ensure_window()
            self.window.present()
            self.window_paintable = Gtk.WidgetPaintable.new(self.window)
            self.window.set_theme("light")
            self.open_started = time.monotonic()
            self.doc = self.window.open_path(str(self.document_path))
            diagnostics = "window.__smokeErrors=[];addEventListener('error',e=>window.__smokeErrors.push({message:e.message,url:e.filename,element:e.target?.outerHTML}),true);addEventListener('unhandledrejection',e=>window.__smokeErrors.push({promise:String(e.reason)}));addEventListener('securitypolicyviolation',e=>window.__smokeErrors.push({csp:e.violatedDirective,blocked:e.blockedURI}));"
            self.doc.web.get_user_content_manager().add_script(WebKit.UserScript.new(diagnostics,
                WebKit.UserContentInjectedFrames.TOP_FRAME, WebKit.UserScriptInjectionTime.START, None, None))
            self.delay(self.startup_diagnostics, 3000)
            self.wait_for(lambda: self.doc.loaded, self.inspect_rendering, "comprehensive document load")
        except Exception as error:
            self.fail(str(error))
        return GLib.SOURCE_REMOVE

    def startup_diagnostics(self):
        if self.doc.ready:
            return
        expression = """({reader:typeof window.reader,ready:document.readyState,html:document.documentElement.outerHTML,
            resources:performance.getEntriesByType('resource').map(x=>({name:x.name,duration:x.duration,transfer:x.transferSize})),
            bridge:typeof window.webkit?.messageHandlers?.reader,errors:window.__smokeErrors||[]})"""
        def diagnostic(value):
            self.record("Startup diagnostics", value, "diagnostic")
            self.snapshot(self.doc, "startup-diagnostic.png", lambda: None)
        self.evaluate(self.doc, expression, diagnostic)

    def inspect_rendering(self):
        self.record("Native document loaded", {"seconds": round(time.monotonic() - self.open_started, 3),
                                               "editable": self.doc.editable, "reason": self.doc.edit_reason,
                                               "issues": self.doc.issues})
        self.require(self.doc.mode == "read", "Documents must open in reading mode")
        self.require(sha(self.document_path) == self.initial_hash, "Reading modified the original file")
        # Reading deliberately appears before optional renderers finish. Wait
        # on the application's real readiness barrier, not an arbitrary delay.
        def rendered(message):
            self.doc.call("exportFinished")
            self.require(not message.get("issues"), f"Rendering failed: {message.get('issues')}")
            self.inspect_ready_rendering()
        self.doc.request("prepareExport", self.guard(rendered))

    def inspect_ready_rendering(self):
        expression = """({
          text: document.body.innerText,
          headings: [...document.querySelectorAll('h1,h2,h3')].map(x => x.textContent),
          tables: document.querySelectorAll('table').length,
          math: document.querySelectorAll('.katex').length,
          diagrams: document.querySelectorAll('svg[aria-roledescription],svg .flowchart,svg[id^="mermaid"]').length,
          images: [...document.images].map(x => ({src:x.getAttribute('src'),complete:x.complete,width:x.naturalWidth})),
          editable: [...document.querySelectorAll('[contenteditable="true"]')].length,
          width: innerWidth, scrollWidth: document.documentElement.scrollWidth,
          facade: typeof window.reader.testInsertText
        })"""
        self.evaluate(self.doc, expression, self.rendering_inspected)

    def rendering_inspected(self, dom):
        (self.output / "dom-initial.json").write_text(json.dumps(dom, indent=2, ensure_ascii=False))
        self.require(any("A clearer place" in heading for heading in dom["headings"]), "Heading was not rendered")
        self.require(dom["tables"] >= 1, "GFM table was not rendered")
        self.require(dom["math"] >= 2, "Both inline and display mathematics must render")
        self.require(dom["diagrams"] >= 1, "Mermaid diagram was not rendered")
        self.require(any(image["complete"] and image["width"] > 0 for image in dom["images"]), "Local image did not resolve")
        self.require("remains-code" in dom["text"], "LaTeX code example vanished")
        self.require(dom["scrollWidth"] <= dom["width"] + 2, "Reading page overflows horizontally")
        self.require(not dom["editable"], "Read mode is contenteditable")
        self.record("Real WebKit DOM renders headings, table, math, Mermaid and local image")
        self.doc.request("serialize", self.guard(self.serialization_checked))

    def serialization_checked(self, message):
        self.require(message.get("ok", True), message.get("error", "Serialization failed"))
        markdown = message.get("markdown", "")
        for preserved in ('title: Native rendering verification', 'title="example.py" {1}', '```latex',
                          '[^evidence]', 'local%20image.svg', '<div class="fixture-html">'):
            self.require(preserved in markdown, f"Serialization lost protected source: {preserved}")
        self.require("reader://" not in markdown and "blob:" not in markdown, "Internal resource URL leaked into Markdown")
        self.record("Native bridge serialization retains protected sources")
        before = len(self.window.documents)
        duplicate = self.window.open_path(self.document_path.as_uri())
        self.require(duplicate is self.doc and len(self.window.documents) == before, "File URI opened a duplicate tab")
        self.record("Encoded local URI focuses the existing tab")
        self.snapshot(self.doc, "native-light.png", lambda: self.window_snapshot("native-window-light.png", self.dark_snapshot))

    def snapshot(self, doc, filename, then):
        @self.guard
        def captured(web, result, _data):
            texture = web.get_snapshot_finish(result)
            path = self.output / filename
            self.require(texture.save_to_png(str(path)), "Failed to save WebKit snapshot")
            self.record("Native WebKit snapshot", str(path))
            then()
        doc.web.get_snapshot(WebKit.SnapshotRegion.VISIBLE, WebKit.SnapshotOptions.NONE, None, captured, None)

    def dark_snapshot(self):
        self.window.set_theme("dark")
        self.delay(lambda: self.evaluate(self.doc, "document.documentElement.dataset.theme", self.dark_verified))

    def dark_verified(self, theme):
        self.require(theme == "dark", "Dark theme was not applied to the WebKit document")
        self.snapshot(self.doc, "native-dark.png", lambda: self.window_snapshot("native-window-dark.png", self.narrow_snapshot))

    def window_snapshot(self, filename, then, attempt=0):
        width, height = self.window.get_width(), self.window.get_height()
        snapshot = Gtk.Snapshot.new()
        self.window_paintable.snapshot(snapshot, width, height)
        node = snapshot.to_node()
        if node is None and attempt < 5:
            self.window.queue_draw()
            self.delay(lambda: self.window_snapshot(filename, then, attempt + 1), 200)
            return
        self.require(node is not None, "Native window snapshot was empty")
        viewport = Graphene.Rect().init(0, 0, width, height)
        texture = self.window.get_native().get_renderer().render_texture(node, viewport)
        path = self.output / filename
        self.require(texture.save_to_png(str(path)), "Could not save native window snapshot")
        self.record("Whole native window snapshot", str(path))
        then()

    def narrow_snapshot(self):
        self.window.set_theme("light")
        self.window.set_default_size(620, 820)
        self.window.zoom_by(.25)
        self.delay(lambda: self.evaluate(self.doc, "({width:innerWidth,scrollWidth:document.documentElement.scrollWidth})", self.narrow_verified))

    def narrow_verified(self, dimensions):
        self.require(dimensions["width"] <= 700, f"Window did not narrow: {dimensions}")
        self.require(dimensions["scrollWidth"] <= dimensions["width"] + 2, "Narrow document overflows horizontally")
        self.snapshot(self.doc, "native-narrow.png", self.before_export)

    def before_export(self):
        self.window.set_default_size(1120, 820)
        self.window.zoom_by(0, reset=True)
        self.doc.request("prepareExport", self.guard(self.export_readiness))

    def export_readiness(self, message):
        self.require(message.get("ok", True), message.get("error", "Export preparation failed"))
        self.require(not message.get("issues"), f"Export has unresolved content: {message.get('issues')}")
        (self.output / "native-document.pdf").unlink(missing_ok=True)
        self.window.prepare_pdf(self.doc, str(self.output / "native-document.pdf"), done=self.guard(self.exported))

    def exported(self, okay):
        self.require(okay, "Native PDF export failed")
        pdf = self.output / "native-document.pdf"
        self.require(pdf.exists() and pdf.read_bytes().startswith(b"%PDF"), "Export did not produce a PDF")
        if shutil.which("pdftotext"):
            text = subprocess.check_output(["pdftotext", str(pdf), "-"], text=True)
            self.require(all(re.search(r"\b" + label + r"\b", text) for label in ("Read", "Edit", "Save")),
                         "PDF lost Mermaid diagram labels")
        self.require(sha(self.document_path) == self.initial_hash, "PDF export changed the original")
        self.record("Native A4 PDF export", {"path": str(pdf), "bytes": pdf.stat().st_size})
        if self.actual_hash:
            actual = self.window.open_path(str(ACTUAL_README))
            self.wait_for(lambda: actual.loaded, lambda: self.actual_checked(actual), "representative Markdown document")
        else:
            self.record("Actual README", "File not present", "skipped")
            self.start_fidelity_edit()

    def actual_checked(self, actual):
        self.require(sha(ACTUAL_README) == self.actual_hash, "Actual README was modified")
        self.record("Representative Markdown document opened unchanged", {"editable": actual.editable, "reason": actual.edit_reason,
                                                                   "issues": actual.issues})
        self.snapshot(actual, "native-actual-readme.png", self.start_fidelity_edit)

    def start_fidelity_edit(self):
        self.fidelity_path = self.fixtures / "fidelity.md"
        self.fidelity_path.write_text(COMPREHENSIVE)
        self.fidelity_doc = self.window.open_path(str(self.fidelity_path))
        self.wait_for(lambda: self.fidelity_doc.loaded, self.fidelity_loaded, "fidelity editing fixture")

    def fidelity_loaded(self):
        self.require(self.fidelity_doc.editable, f"Comprehensive document cannot be visually edited: {self.fidelity_doc.edit_reason}")
        self.window.mode_changed("edit")
        self.wait_mode(self.fidelity_doc, "edit", self.insert_fidelity_edit)

    def insert_fidelity_edit(self):
        self.fidelity_doc.call("testInsertText", " Fidelity edit retained.")
        self.wait_for(lambda: self.fidelity_doc.dirty, self.capture_editor, "actual comprehensive visual edit")

    def capture_editor(self):
        self.window_snapshot("native-window-editor.png", lambda: self.window.save(self.fidelity_doc, done=self.guard(self.fidelity_saved)))

    def fidelity_saved(self, okay):
        self.require(okay, "Native save of comprehensive visual edit failed")
        markdown = self.fidelity_path.read_text()
        for preserved in ('title: Native rendering verification', 'title="example.py" {1}', '```latex',
                          '[^evidence]', 'local%20image.svg', '<div class="fixture-html">', 'Fidelity edit retained.'):
            self.require(preserved in markdown, f"Actual visual edit lost protected source: {preserved}")
        self.require("reader://" not in markdown and "blob:" not in markdown, "Resource URL leaked during actual edit")
        self.record("Actual comprehensive visual edit/save retains source and protected syntax")
        self.start_editing()

    def start_editing(self):
        self.edit_doc = self.window.open_path(str(self.edit_path))
        self.wait_for(lambda: self.edit_doc.loaded, self.edit_loaded, "editing fixture")

    def edit_loaded(self):
        self.require(self.edit_doc.editable, f"Simple Markdown cannot be edited: {self.edit_doc.edit_reason}")
        self.window.mode_changed("edit")
        self.wait_mode(self.edit_doc, "edit", lambda: self.evaluate(
            self.edit_doc, "typeof window.reader.testInsertText", self.edit_facade_checked))

    def edit_facade_checked(self, facade):
        self.require(facade == "function", "Frontend testInsertText facade is unavailable")
        self.edit_doc.call("testInsertText", " Native edit café λ.")
        self.wait_for(lambda: self.edit_doc.dirty, self.save_edit, "Milkdown transaction reaching the native dirty bridge")

    def save_edit(self):
        self.require("Native edit café λ." not in self.edit_path.read_text(), "Editing wrote before explicit Save")
        self.unsaved_pdf = self.output / "native-unsaved-letter.pdf"
        self.unsaved_pdf.unlink(missing_ok=True)
        self.window.prepare_pdf(self.edit_doc, str(self.unsaved_pdf), paper="na_letter", done=self.guard(self.unsaved_exported))

    def unsaved_exported(self, okay):
        self.require(okay and self.unsaved_pdf.exists(), "Export of unsaved edits failed")
        self.require("Native edit café λ." not in self.edit_path.read_text(), "PDF export silently saved edits to Markdown")
        self.require(self.edit_doc.dirty, "PDF export cleared unsaved state")
        if shutil.which("pdftotext"):
            pdf_text = subprocess.check_output(["pdftotext", str(self.unsaved_pdf), "-"], text=True)
            self.require("Native edit café" in pdf_text, "Export omitted unsaved visual edits")
        if shutil.which("pdfinfo"):
            information = subprocess.check_output(["pdfinfo", str(self.unsaved_pdf)], text=True)
            self.require("612 x 792" in information, "Native Letter paper selection did not reach the PDF")
        self.record("Export includes unsaved edits on Letter paper without saving the Markdown")
        self.window.save(self.edit_doc, done=self.guard(self.edit_saved))

    def edit_saved(self, okay):
        self.require(okay, "Explicit native Save failed")
        self.require("Native edit café λ." in self.edit_path.read_text(), "Saved edit missing from disk")
        self.require(not self.edit_doc.dirty, "Save did not clear dirty state")
        self.record("Visual editor transaction and explicit native Save preserve Unicode")
        replacement = self.edit_path.with_suffix(".replacement")
        replacement.write_text(self.edit_path.read_text() + "\nAgent atomic update.\n")
        os.replace(replacement, self.edit_path)
        self.wait_for(lambda: self.edit_doc.loaded and "Agent atomic update." in self.edit_doc.text,
                      self.refreshed, "atomic agent update")

    def refreshed(self):
        self.record("Native directory watcher detects atomic file replacement")
        self.wait_mode(self.edit_doc, "edit", self.insert_conflicting_edit)

    def insert_conflicting_edit(self):
        self.edit_doc.call("testInsertText", " Unsaved local change.")
        self.wait_for(lambda: self.edit_doc.dirty, self.create_conflict, "unsaved local change")

    def create_conflict(self):
        self.external_text = self.edit_path.read_text() + "\nConcurrent agent change.\n"
        self.edit_path.write_text(self.external_text)
        self.wait_for(lambda: self.edit_doc.conflict, self.check_conflict, "concurrent change conflict")

    def check_conflict(self):
        self.require("Unsaved local change." in self.edit_doc.text, "Conflict lost the editor buffer")
        self.window.save(self.edit_doc, done=self.guard(self.conflicting_save_checked))

    def conflicting_save_checked(self, okay):
        self.require(not okay, "Conflicting Save was not blocked")
        self.require(self.edit_path.read_text() == self.external_text, "Conflicting Save overwrote the agent's update")
        self.record("Concurrent disk edit blocks Save and retains the local buffer")
        self.edit_doc.write_draft()
        drafts = self.app.store.load_drafts()
        self.require(any("Unsaved local change." in item.get("text", "") for item in drafts.values()), "Recovery draft lost edited text")
        self.record("Local recovery draft retains unsaved content")
        copy = self.fixtures / "copies/edited copy.md"
        copy.parent.mkdir()
        self.window.save_to(self.edit_doc, copy, done=self.guard(self.copy_saved))

    def copy_saved(self, okay):
        self.require(okay, "Save a Copy failed")
        self.require("Unsaved local change." in self.edit_doc.path.read_text(), "Copy lost unsaved edits")
        copied = self.edit_doc.path.read_text()
        self.require("../local%20image.svg" in copied and "../linked.md" in copied, "Save a Copy failed to rebase relative references")
        self.require(self.edit_path.read_text() == self.external_text, "Save a Copy changed original")
        self.record("Save a Copy retains edits without modifying the conflicted original")
        benchmark = self.fixtures / "performance-100kb.md"
        paragraph = "A document should remain comfortable to read. This paragraph measures local rendering without external assets.\n\n"
        benchmark.write_text("# Rendering performance\n\n" + paragraph * (100_000 // len(paragraph) + 1))
        self.benchmark_started = time.monotonic()
        benchmark_doc = self.window.open_path(str(benchmark))
        self.wait_for(lambda: benchmark_doc.loaded, self.benchmark_finished, "100 KB document rendering")

    def benchmark_finished(self):
        seconds = round(time.monotonic() - self.benchmark_started, 3)
        self.record("100 KB local rendering target", {"seconds": seconds, "target_seconds": 2.0},
                    "passed" if seconds <= 2 else "warning")
        self.finish()

    def fail(self, reason):
        if not self.done:
            self.failed = True
            self.record("Native integration", reason, "failed")
            self.finish()
        return GLib.SOURCE_REMOVE

    def finish(self):
        if self.done:
            return
        self.done = True
        try:
            for path, expected, label in ((self.document_path, self.initial_hash, "Comprehensive fixture"),
                                          (ACTUAL_README, self.actual_hash, "Actual user README")):
                if expected:
                    try:
                        unchanged = sha(path) == expected
                        self.record(label + " source hash", "unchanged" if unchanged else "CHANGED", "passed" if unchanged else "failed")
                        self.failed |= not unchanged
                    except OSError as error:
                        self.failed = True
                        self.record(label + " source hash", str(error), "failed")
            summary = {"passed": not self.failed, "elapsed_seconds": round(time.monotonic() - self.start_time, 2),
                       "results": self.results, "isolated_run": str(self.run_dir),
                       "frontend_index_sha256": self.build_hash,
                       "not_covered": ["Physical keyboard/clipboard input", "Interactive file picker", "File-manager double-click", "Visual inspection of the produced PNG/PDF artifacts"]}
            (self.output / "native-results.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False))
            print(json.dumps({"summary": str(self.output / "native-results.json"), "passed": not self.failed}), flush=True)
        except Exception as error:
            self.failed = True
            print(f"Could not write native result summary: {error}", file=sys.stderr, flush=True)
        finally:
            if self.window:
                for doc in self.window.documents:
                    try:
                        doc.cleanup()
                    except Exception:
                        pass
            self.app.quit()

    def run(self):
        self.app.run([sys.argv[0]])
        return 1 if self.failed or not self.done else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=PROJECT / "work/native-check")
    args = parser.parse_args()
    raise SystemExit(NativeSmoke(args.output).run())
