import { describe,it,expect } from 'vitest';
import {canonical,assertRoundtrip,splitFrontmatter,protectionPlugin,parser,rebaseMarkdown,canonicalEditorModel} from './markdown';
describe('document preservation',()=>{
  it('retains frontmatter separately including delimiters',()=>{const input='---\r\ntitle: A\r\n---\r\n# Heading';expect(splitFrontmatter(input)).toEqual({prefix:'---\r\ntitle: A\r\n---\r\n',body:'# Heading'});});
  it('retains empty YAML frontmatter',()=>expect(splitFrontmatter('---\n---\n# Doc')).toEqual({prefix:'---\n---\n',body:'# Doc'}));
  it('rebases only local destinations, preserving extensions and source bytes',()=>{const input='---\n---\n[[note|Label]]\n\n![a](local.png) [nested](<../a%20b.md#head>)\n\n```md title="example"\n[x](local.md)\n```\n';expect(rebaseMarkdown(input,'/a','/a/copy')).toBe('---\n---\n[[note|Label]]\n\n![a](../local.png) [nested](<../../a%20b.md#head>)\n\n```md title="example"\n[x](local.md)\n```\n');});
  it('rebases HTML attributes including unquoted/entity URLs without changing displayed text',()=>expect(rebaseMarkdown('<img src=local.png>\n\n<a href="assets/a&amp;b.md">Link</a>\n\n<div>src="guide.md"</div>\n','/a','/a/copy')).toBe('<img src=../local.png>\n\n<a href="../assets/a%26b.md">Link</a>\n\n<div>src="guide.md"</div>\n'));
  it('respects HTML quote boundaries and raw script text when rebasing',()=>{const input='<div title="x > y src=keep.md"><img title="src=ignore.png" src="local.png"></div>\n\n<script>const text = `<img src="keep.png">`;</script>\n';expect(rebaseMarkdown(input,'/a','/a/copy')).toBe(input.replace('src="local.png"','src="../local.png"'));});
  it('uses the first reference definition and case-insensitive footnote identity',()=>{const source='[link][id] and A[^NOTE].\n\n[id]: first.md\n[id]: second.md\n\n[^note]: text';const processor=parser().use(protectionPlugin);const tree=processor.runSync(processor.parse(source),source) as any;expect(tree.children[0].children[0].url).toBe('first.md');expect(tree.children[0].children.find((n:any)=>n.kind==='footnoteReference').target).toBe('note');});
  it('editor model guard ignores generated IDs but catches dropped content/formatting',()=>{const a={type:'doc',content:[{type:'heading',attrs:{level:2,id:'generated'},content:[{type:'text',text:'Keep',marks:[{type:'strong'}]}]},{type:'paragraph'}]};const b={type:'doc',content:[{type:'heading',attrs:{level:2,id:''},content:[{type:'text',text:'Keep',marks:[{type:'strong'}]}]}]};expect(canonicalEditorModel(a)).toBe(canonicalEditorModel(b));expect(canonicalEditorModel(a)).not.toBe(canonicalEditorModel({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Keep'}]}]}));});
  it('accepts formatting normalization but rejects lost text',()=>{expect(()=>assertRoundtrip('**bold**\n\n- one','__bold__\n\n* one\n')).not.toThrow();expect(()=>assertRoundtrip('Keep every word','Keep word')).toThrow();});
  it('distinguishes math from a latex code example',()=>expect(canonical('```latex\nx^2\n```')).not.toEqual(canonical('$$\nx^2\n$$')));
  it('rejects lost code metadata, footnotes, links, and HTML',()=>{for(const [a,b] of [['```js title="a"\nx\n```','```js\nx\n```'],['A[^key]\n\n[^key]: note','A'],['[a](../a%20b.md)','[a](reader://asset/1)'],['<span>source</span>','source']])expect(()=>assertRoundtrip(a,b)).toThrow();});
  it('protects math, html, definitions and footnotes with source',()=>{const source='A $x^2$ and [^key].\n\n[^key]: foot **bold**\n\n<div data-extra="a">html</div>\n';const processor=parser().use(protectionPlugin);const result=processor.runSync(processor.parse(source),source) as any;expect(result.children[0].children.some((n:any)=>n.type==='readerInline'&&n.value==='$x^2$')).toBe(true);expect(result.children[1].value).toBe('[^key]: foot **bold**');expect(result.children[2].value).toContain('data-extra');});
});
